#!/bin/env python2

import sys
from threading  import Thread

def my_print(some_str):
    sys.stderr.write(some_str+"\n")

def print_received():
    while True:
        line = sys.stdin.readline()
        my_print("received from host: " + line)

if __name__ == '__main__':
    my_input = open("./my_input", "r")

    stdin_to_stderr = Thread(target=print_received)
    stdin_to_stderr.daemon = True
    stdin_to_stderr.start()

    for line in my_input:
        my_print("received localy: " + line)
        sys.stdout.write(line)
        sys.stdout.flush()


    my_input.close()

    
    




